### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 Model ID is invalid. It should start with 3 letters.

### ISSUE THREAD

**Issue by nataly-obr** [googleapis/python-automl#107]
#### Environment details

  - OS type and version: Ubuntu 18.04.5 LTS
  - Python version: 3.7.5, 3.6.9, 2.7.17
  - pip version: pip 20.2.4
  - `google-cloud-automl` version: 2.1.0

#### Steps to reproduce

  1. I run Code Sample for Predict entity extraction (https://cloud.google.com/natural-language/automl/docs/samples/automl-language-entity-extraction-predict)
  2. I set the project_id and model_id variables and changed region. 

#### Code example

```python
from google.cloud import automl

# TODO(developer): Uncomment and set the following variables
project_id = "YOUR_PROJECT_ID"
model_id = "YOUR_MODEL_ID" 
content = "text to predict"

prediction_client = automl.PredictionServiceClient()

# Get the full path of the model.
model_full_id = automl.AutoMlClient.model_path(
    project_id, "europe-west4", model_id
)

# Supported mime_types: 'text/plain', 'text/html'
# https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#textsnippet
text_snippet = automl.TextSnippet(
    content=content, mime_type="text/plain"
)
payload = automl.ExamplePayload(text_snippet=text_snippet)

response = prediction_client.predict(name=model_full_id, payload=payload)
```

#### Error
```
Traceback (most recent call last):
  File "/home/.../lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/.../lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/.../lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Model ID is invalid. It should start with 3 letters."
	debug_error_string = "{"created":"@1608039810.454427520","description":"Error received from peer ipv4:173.194.221.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Model ID is invalid. It should start with 3 letters.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../mytest.py", line 44, in <module>
    response = prediction_client.predict(name=model_full_id, payload=payload)
  File "/home/.../lib/python3.7/site-packages/google/cloud/automl_v1/services/prediction_service/client.py", line 413, in predict
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/.../lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/.../lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Model ID is invalid. It should start with 3 letters.

Process finished with exit code 1

```
Strange error, because on the Google Cloud Platform (where I created and trained my model) model ID consists of 19 digits, no letters.

**Comment by munkhuushmgl** [comment]
I think its asking for model name (meaning the name with prefix IOD, ICN, TRL and etc..  )
![image](https://user-images.githubusercontent.com/45373284/102288566-9b641500-3ef1-11eb-91b0-d67117d7149c.png)

You can find the model name from your google console

**Comment by nataly-obr** [comment]
> hink its asking for model name (meaning the name with prefix IOD, ICN,

I've tried that too. Error:
`google.api_core.exceptions.NotFound: 404 Invalid resource ID`

**Comment by nataly-obr** [comment]
> I think its asking for model name (meaning the name with prefix IOD, ICN, TRL and etc.. )
> ![image](https://user-images.githubusercontent.com/45373284/102288566-9b641500-3ef1-11eb-91b0-d67117d7149c.png)
> 
> You can find the model name from your google console

Thank you, but my console (AI Platform (Unified)) looks differently. Am I looking in the wrong place?

![Screenshot from 2020-12-16 14-35-02](https://user-images.githubusercontent.com/59837137/102343812-1558d480-3fac-11eb-9767-ea1598d0347b.png)

**Comment by munkhuushmgl** [comment]
I see, were you able to solve your problem ?

**Comment by nataly-obr** [comment]
> I see, were you able to solve your problem ?

No, not really. I tried a provided sample request. I also changed location for "europe-west4".

```python

from google.cloud import aiplatform

def predict_custom_model_sample(endpoint: str, instance: dict, parameters_dict: dict):
    #client_options = dict(api_endpoint="us-central1-prediction-aiplatform.googleapis.com")
    client_options = dict(api_endpoint="europe-west4-prediction-aiplatform.googleapis.com")
    client = aiplatform.PredictionServiceClient(client_options=client_options)
    from google.protobuf import json_format
    from google.protobuf.struct_pb2 import Value

    # The format of the parameters must be consistent with what the model expects.
    parameters = json_format.ParseDict(parameters_dict, Value())

    # The format of the instances must be consistent with what the model expects.
    instances_list = [instance]
    instances = [json_format.ParseDict(s, Value()) for s in instances_list]
    response = client.predict(
        endpoint=endpoint, instances=instances, parameters=parameters
    )

    print("response")
    print(" deployed_model_id:", response.deployed_model_id)
    predictions = response.predictions
    print("predictions")
    for prediction in predictions:
        print(" prediction:", dict(prediction))



predict_custom_model_sample(
    "projects/165...83/locations/europe-west4/endpoints/743...432",
    {"content": "test"},
    {}
)
```
Error
`Traceback (most recent call last):
  File "/snap/pycharm-community/222/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/222/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/.../mytest.py", line 173, in <module>
    {}
  File "/home/.../mytest.py", line 147, in predict_custom_model_sample
    client = aiplatform.PredictionServiceClient(client_options=client_options)
AttributeError: module 'google.cloud.aiplatform' has no attribute 'PredictionServiceClient'
python-BaseException`

**Comment by munkhuushmgl** [comment]
I think you were supposed to pass END_POINT_ID instead `europe-west4-prediction-aiplatform.googleapis.com`

Like this one:

https://github.com/googleapis/python-aiplatform/blob/1a302d232d868a96bf6a41cbf92a550edcdb0673/samples/snippets/predict_image_object_detection_sample_test.py#L21-L34

**Comment by nataly-obr** [comment]
> I think you were supposed to pass END_POINT_ID instead `europe-west4-prediction-aiplatform.googleapis.com`
> 
> Like this one:
> 
> https://github.com/googleapis/python-aiplatform/blob/1a302d232d868a96bf6a41cbf92a550edcdb0673/samples/snippets/predict_image_object_detection_sample_test.py#L21-L34

Thank you! I finally made it. It was correct though to pass `europe-west4-prediction-aiplatform.googleapis.com`. 

Like here (https://github.com/googleapis/python-aiplatform/blob/1a302d232d868a96bf6a41cbf92a550edcdb0673/samples/snippets/predict_text_entity_extraction_sample.py)

My problem was solved by creating a key for App Engine default service account and using this key instead of a key for Service Account.
 
![Screenshot from 2020-12-21 16-00-22](https://user-images.githubusercontent.com/59837137/102779709-c3e28800-43a5-11eb-9cb2-d03978e922df.png)

**Comment by munkhuushmgl** [comment]
Great, I am closing this issue, feel free to reopen if u still experiencing any other issue

**Comment by pavelkozhokar** [comment]
> > I think you were supposed to pass END_POINT_ID instead `europe-west4-prediction-aiplatform.googleapis.com`
> > Like this one:
> > https://github.com/googleapis/python-aiplatform/blob/1a302d232d868a96bf6a41cbf92a550edcdb0673/samples/snippets/predict_image_object_detection_sample_test.py#L21-L34
> 
> Thank you! I finally made it. It was correct though to pass `europe-west4-prediction-aiplatform.googleapis.com`.
> 
> Like here (https://github.com/googleapis/python-aiplatform/blob/1a302d232d868a96bf6a41cbf92a550edcdb0673/samples/snippets/predict_text_entity_extraction_sample.py)
> 
> My problem was solved by creating a key for App Engine default service account and using this key instead of a key for Service Account.
> 
> ![Screenshot from 2020-12-21 16-00-22](https://user-images.githubusercontent.com/59837137/102779709-c3e28800-43a5-11eb-9cb2-d03978e922df.png)

Hi @nataly-obr   I got the same problem, but have no such "App Engine default service account" in service account list.. 
Could you advise?

**Comment by nataly-obr** [comment]
> Hi @nataly-obr I got the same problem, but have no such "App Engine default service account" in service account list..
> Could you advise?

From documentation:
"After you create an App Engine application, the App Engine default service account is created and used as the identity of your App Engine app."
[https://cloud.google.com/appengine/docs/standard/python3/service-account](url)
