### ISSUE TITLE
The `params` parameter is ignored in `batch_predict()` method

### ISSUE THREAD

**Issue by elbernante** [googleapis/python-automl#109]
Passing a value to the `params` parameter in the `batch_predict()` method of `TablesClient` class does not have any effect.

For example, passing the value `params={'feature_importance':  'true'}` to `batch_predict()` is supposed to have feature importance generated along with the output, but there was none.

#### Environment details
  - OS type and version: Ubuntu 18.04.5 LTS
  - Python version: 3.5.2, 3.6.10, 3.7.2, 3.8.6
  - pip version: 20.2.4
  - `google-cloud-automl` version: 2.1.0

#### Steps to reproduce

  1.  Make a batch prediction with `params` (e.g. `params={'feature_importance':  'true'}`).
  2. Invoke the request.
  3. Notice that the generated output does not generate feature importance.

#### Code example

```python
from google.cloud import automl_v1beta1

client = automl_v1beta1.TablesClient(project='my-project', region='us-central1')

client.batch_predict(
    bigquery_input_uri='bq://my-project.dataset.table',
    bigquery_output_uri='bq://my-project',
    model_display_name='my_model',
    params={'feature_importance': 'true'}
)

```

**Comment by munkhuushmgl** [comment]
I will take a look at your PR soon sometime this week. @elbernante
