### ISSUE TITLE
AutoML regional bucket in the same location and with same storage class as AutoML

### ISSUE THREAD

**Issue by Grinnbob** [googleapis/python-automl#112]
Error with region\location - how to check and change AutoML location? I'm trying to run classification automl and uploading data in google cloud storage with location us-central1 but I can't create a dataset with this location.

#### Environment details

- Python 3.6.9
- pip 19.3.1
- linux (Google Colab)
- google-cloud-automl Version: 2.1.0

#### Steps to reproduce

  1. create bucket
  `gsutil mb -b on -l us-central1 {bucket_path}/`
  2. upload all files in gsu
  `gsutil cp {my_file_path} {bucket_path}`
  3. create dataset
  https://github.com/googleapis/python-automl/blob/master/samples/snippets/language_text_classification_create_dataset.py
  4. import data into a dataset https://github.com/googleapis/python-automl/blob/master/samples/snippets/import_dataset.py 

#### Code example

```
dataset_full_id = client.dataset_path(
    project_id, "us-central1", dataset_id
)

input_uris = path.split(",")
gcs_source = automl.GcsSource(input_uris=input_uris)
input_config = automl.InputConfig(gcs_source=gcs_source)

response = client.import_data(name=dataset_full_id, input_config=input_config)

print("Processing import...")
print("Data imported. {}".format(response.result()))
```

#### Stack trace
```
FailedPrecondition: 400 Cannot move files across regions. Please use a regional bucket in the same location and with same storage class as AutoML. Required Location: us-central1, required location type: Region, required storage class: Standard.
```

**Comment by munkhuushmgl** [comment]
`us-central1` location is already hardcoded in the sample
https://github.com/googleapis/python-automl/blob/b89fb0070fd4eeb0306d8f584e31da9d8b3fa52c/samples/snippets/language_text_classification_create_dataset.py#L28

Therefore, if you are using that create_dataset samples, u already creating dataset in the `us-central1` location.

**Comment by Grinnbob** [comment]
I follow [this guide](https://cloud.google.com/natural-language/automl/docs/datasets#code_samples) step by step, but I still cannot understand why this error occurs - the us-central1 is used everywhere

**Comment by munkhuushmgl** [comment]
From what I can tell, your bucket location or dataset's location are not same.

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue. Feel free to reopen this issue.

**Comment by winter-code** [comment]
Hi, is this issue resolved? I have my bucket in the `us-cenral1` region and the AutoML dataset as global. I'm following the documentation as well. I'm using the UI to import the csv.
Still getting the cross region error. Can somebody help on this?

**Comment by mmortazavi** [comment]
From GCP customers in EU, it is strictly required data, dataset, model etc. to remain in EU. I wonder how that is not possible while bucket is in EU (NL), dataset and as such Model (export) should be in us-central? Funny thing, there is a workaround that I am not a fan of, but one can export to a bucket in us-central, and Transfer it from there to the bucket in EU! But straightforward not. It has been over 2 years...

**Comment by SmartDev-0205** [comment]
My dataset is us-central1 and my bucket is also us-central1 with region location type.
Also storage type is also standard.
But I get this error :(
What is the solution?
