### ISSUE TITLE
API access to observe specific examples of model performance for automl vision object-detection

### ISSUE THREAD

**Issue by Eslsamu** [googleapis/python-automl#123]
About AutoML Vision Object Detection:
I am having the problem that I need to sometimes inspect specific examples after the training is finished. 
I want to do this programmatically, since I made my own platform which interacts with Google AutoML. 
What I want is already available on the UI:
[Evaluating models](https://cloud.google.com/vision/automl/docs/evaluate#tp-fn-fp-images)
I would suggest to add an API call that takes the ID of the model-evaluation as an input and 
returns the predicted label/bb and the true label/bb for each image in the dataset.

**Comment by morgandu** [comment]
Thanks for using Google Cloud AutoML Vision, as what you suggested is not supported, you may request this feature by logging your issue using the public tracker. https://cloud.google.com/support/docs/issue-trackers?authuser=0 -> "Create new Cloud Vision issue".
--

**Comment by morgandu** [comment]
Follow up suggestion on the user request.

The UI feature you are looking at has a drag bar that you can define the confidence threshold, which will give you the TP, TN, FP, FN from the selected threshold value from the UI input. For this particular customization, it may be easier and more effective if the threshold based evaluation is implemented on the end user side given the raw prediction result.
