### ISSUE TITLE
for the automl tables_client to be able to export the test dataset 

### ISSUE THREAD

**Issue by tinyneutrino** [googleapis/python-automl#148]
it makes sense in an automation way to be able to download your test dataset to BigQuery or as a csv for custom evaluation.
Right now I have to download the test set manually as described in the guide 
https://cloud.google.com/automl-tables/docs/evaluate#downloading_your_test_dataset_to

**Comment by telpirion** [comment]
This looks like a feature request. Please redirect your request here:
https://issuetracker.google.com/issues/new?component=625378
