### ISSUE TITLE
AutoML tables: changing just a col's data type apparently also changes the nullability status

### ISSUE THREAD

**Issue by amygdala** [googleapis/python-automl#2]
With the automl tables client libs, I'm seeing that a call like this to change the data type of a column, where that column is initially set to be `Nullable`:
```
client.update_column_spec(
          dataset_display_name='my dataset',
          column_spec_display_name='col_name',
          type_code='CATEGORY')
```

also **changes the nullability**-- it changes the col to from nullable to non-nullable.

(I haven't tried the case where the col starts out as non-nullable).

(The [wrapper code](https://github.com/googleapis/google-cloud-python/blob/master/automl/google/cloud/automl_v1beta1/tables/tables_client.py#L1142) looks okay on the face of it... )

**Comment by munkhuushmgl** [comment]
@helinwang Hey is there any update or internal bug logged somewhere?

**Comment by amygdala** [comment]
b/148677380

**Comment by kweinmeister** [comment]
Closing this issue for now, but please reopen if you are seeing this behavior.
