### ISSUE TITLE
not able to `batch_predict` to a `bigquery_output_uri` 

### ISSUE THREAD

**Issue by bobcolner** [googleapis/python-automl#20]
Hi, I'm trying to run a batch_predict and output to a bigquery table.  The codde below fails with the following error message. I am able to write the results to gcs fine.

Do I need to create the `bq://emerald-skill-201716.ml.premium_d30_scores` table beforehand? If so what schema?

Thanks!

```
output_future = automl_tables_client.batch_predict(
        bigquery_input_uri='bq://project_id.ml.premium_d30_inference',
        bigquery_output_uri='bq://project_id.ml.premium_d30_scores',
        # gcs_output_uri_prefix='gs://bucket/automl_predictions/',
        model_display_name='premium_d30_train_sample'
    ).result()
```

`InvalidArgument: 400 List of found errors:	1.Field: output_config.bigquery_destination.output_uri; Message: Invalid BigQuery destination path: bq://project_id.ml.premium_d30_scores	
`

**Comment by bobcolner** [comment]
bump

**Comment by bobcolner** [comment]
any ideas? do you need more information from me? Do you *care* about my experience as a paying customer?

**Comment by munkhuushmgl** [comment]
@bobcolner I am looking into it!

**Comment by munkhuushmgl** [comment]
my setup:
```google-cloud-automl==0.10.0

client = automl_v1beta1.TablesClient(
    project="your-project-id", region="us-central1"
)

client.batch_predict(
    bigquery_input_uri="bq://product-stockout.product_stockout.batch_prediction_inputs",
    bigquery_output_uri="bq://project-id",
    model_display_name="your-model-name",
).result()
```

I was able to get the same error by passing wrong format. for example: ``bq://project-id:test_dataset.test_table, bq://project-id:test_dataset.test_table/, bq://project-id:test_dataset ... etc..``

  `google.api_core.exceptions.InvalidArgument: 400 List of found errors:	1.Field: output_config.bigquery_destination.output_uri; Message: Invalid BigQuery destination path:`



That error went away when I only pass ```bq://projectId```

I refer to this proto
https://cloud.google.com/automl/docs/reference/rest/v1beta1/BigQueryDestination

**Comment by munkhuushmgl** [comment]
@bobcolner Please let me know if that helps or not

**Comment by munkhuushmgl** [comment]
```bigqueryDestination pointing to a BigQuery project must be set. In the given project a new dataset will be created with name

export_data_<automl-dataset-display-name>_<timestamp-of-export-call> where will be made BigQuery-dataset-name compatible (e.g. most special characters will become underscores), and timestamp will be in YYYY_MM_DDThh_mm_ss_sssZ "based on ISO-8601" format. In that dataset a new table called primary_table will be created, and filled with precisely the same data as this obtained on import.```

**Comment by munkhuushmgl** [comment]
Closing this issue, with the setup I provided, @bobcolner you should be able to resolve this issue.

Feel free to reopen if you still having trouble with this

Thanks

**Comment by muscovitebob** [comment]
[The documentation](https://googleapis.dev/python/automl/latest/gapic/v1beta1/tables.html) is wrong then. It states, for the `batch_predict` call:
```
bigquery_output_uri (Optional[str]) – The BigQuery table to output data to. This must be supplied if gcs_output_uri_prefix is not.
```
Whereas the only argument that is actually accepted is the project identifier.
