### ISSUE TITLE
chore: references to "python-docs-samples" master branch

### ISSUE THREAD

**Issue by nicain** [googleapis/python-automl#245]
During the master --> main migration, I noticed references that point to the master branch of https://github.com/googleapis/python-docs-samples

After that repo is migrated, we will need to circle back to this repo (and potentially others) and fix these references

- [x] samples/AUTHORING_GUIDE.md
- [x] samples/CONTRIBUTING.md

xref: googleapis/google-cloud-python#10579

**Comment by kweinmeister** [comment]
@nicain it looks like that repo has been migrated already. Also note that it's located in the `GoogleCloudPlatform` org.

**Comment by nicain** [comment]
Resolved by https://github.com/googleapis/python-automl/pull/297
