### ISSUE TITLE
AutoML: support model export via the automl tables client lib

### ISSUE THREAD

**Issue by amygdala** [googleapis/python-automl#3]
It would be great to support automl tables [model export](https://cloud.google.com/automl-tables/docs/model-export) as part of this API surface: https://github.com/googleapis/google-cloud-python/blob/master/automl/google/cloud/automl_v1beta1/tables/tables_client.py

(cc @helinwang @sirtorry )

**Comment by amygdala** [comment]
For planning purposes, a customer is very interested in this:
"As for export - this is a critical feature for us. We have already begun architecting our CI/CD pipeline, and automating model export and deployment is key to it.

Do you know when this feature is scheduled to be delivered? It will be difficult for us to move to production with AutoML tables without it.  "

**Comment by sirtorry** [comment]
library in maintenance. further developments will be made in vertex ai sdk
