### ISSUE TITLE
Choosing machines types that your training used

### ISSUE THREAD

**Issue by Arowne** [googleapis/python-automl#31]
Hi, I'm using the Google automl Tables sdk, unfortunately I'm facing a problem that's beyond me... There is no way to improve my training by choosing the power of my machine (virtual cores, memory ...) it seems that automl jobs actually use the 1n 4 standard (4 cores, 15gb memory). It will be cool to be able to increase the power and the simultaneous calculation for our training.

**Comment by danoscarmike** [comment]
@Arowne thanks for reaching out. I'm moving this issue to the googleapis/python-automl repo where it should get the right eyes on it.

**Comment by gguuss** [comment]
@danoscarmike FYI this issue is out of SLO, if it's been moved, please close.

**Comment by sirtorry** [comment]
thank you for your feedback. we're implementing this into our upcoming library.
