### ISSUE TITLE
Please provide some guidance on the difference between v1beta and v1

### ISSUE THREAD

**Issue by evil-shrike** [googleapis/python-automl#35]
Hi!

I needed to run a AutoML model in batch_predict mode and I tried to find some way to pass input BQ's table and output. But it turned out to be not very clear.
I'd like to share my exprerience and ask for some improvement for documentation.
First of all I looked into BQ's documentation - https://cloud.google.com/vision/automl/docs/predict-batch#automl_batch_predict-python
There's a sample where input and output data are being passed via GCS.
So I went to API doc to look up the reference of batch_predict [method](https://googleapis.dev/python/automl/latest/gapic/v1/api.html#google.cloud.automl_v1.PredictionServiceClient.batch_predict).
And found that there's no an ability to specify any other input and output sources besides gcs. Which looked weird. But then I went to sources on github and found that two versions exist in the repo - v1 and v1beta1.
I wouldn't care but I found `BigQuerySource` and `BigQueryDestination` types in v1beta1. And it was exactly what I needed! 
With REST APIs it's a similar picture: there was BigQuerySource in [v1beta1](https://cloud.google.com/automl/docs/reference/rest/v1beta1/projects.locations.models/batchPredict) and it was removed in v1. 
So we are having two versions of AutoML side-by-side with different APIs and client libs.
Using BigQuery as a source and destination for AutoML is obviously very naturally and handy. It's not quite clear why this ability was removed. 

Obviously v1 is newer than v1beta1. And having a feature in v1beta1 that was removed in v1 provoking using v1beta1 what probably is a bad idea. But it'd be nice to have some guidance for migration and differences description from v1beta1 to v1 then.

**Comment by munkhuushmgl** [comment]
@evil-shrike Sorry to hear that, 
What type of model are you using for batch predict?

Recently, I helped the customer who had a similar issue.

Please take a look the following issue:

https://github.com/googleapis/python-automl/issues/20

**Comment by munkhuushmgl** [comment]
@gguuss I may not be the best person to answer this. Could you answer this question please?
Seems like very broad question

**Comment by gguuss** [comment]
Thanks for reporting the issue, it appears that the bigquery source/destination types that were available during beta were removed for the stable release - this is clear in the REST reference but awkwardly, there are some broken references still left in the RPC reference. Note that sometimes the product teams use the <version><beta> endpoints as an unstable channel and the <version> endpoint for stable but I don't think that's the case in AutoML.

I have reported the issue in the documentation to our team, in the future, when you see these types of issues, you can report it directly from the documentation page and it will reach our writing team. Just look for the Send Feedback button near the "Was this page helpful?" likert range.

I'm following up with the team to make sure this was deliberate, usually there's a good reason for a feature not ending up in GA and hopefully I'll have answer for you.

I'm assuming in your use case you require BigQuery as a src/destination type and cannot use csv files? Is there a reason csv will not work?

**Comment by helinwang** [comment]
> Obviously v1 is newer than v1beta1

I don't think this is true.

My understanding is:
- `v1beta1` is for beta product (e.g., AutoML Tables) or GA product's beta features.
- `v1` is for GA product's GA features

So the way to decide using `v1beta1` vs. `v1` is to check if the product (and feature) you are using is GA or beta.

For `BigQuerySource` and `BigQueryDestination` found in `v1beta1` but not in `v1`. I think it's due to the GA products don't support `BigQuerySource` and `BigQueryDestination`. Which I think is the case for Vision (assuming you are referring to Vision). To check verify it, you can check if the UI support importing / exporting from BigQuery.

**Comment by evil-shrike** [comment]
Hi Helin. I see, thanks for explaining v1 vs v1beta, it helps a lot.
Sorry that I wasn't specific, but I was referring to AutoML Tables not Vision. And UI does have support for input/output in BQ. As AutoML Table isn't in GA, so probably there shouldn't be Table support in v1 at all.

**Comment by helinwang** [comment]
You are welcome.
Yes, for AutoML Tables you should be only using `v1beta`.

**Comment by gguuss** [comment]
Thank you both, I'll go ahead and close the issue as it seems the high-level problem was some confusion on the release tags (beta vs GA), we'll still be tracking the documentation update internally and hopefully this will be made more clear in the docs.
