### ISSUE TITLE
[Doc] Documentation for types has repeated members and broken markup

### ISSUE THREAD

**Issue by evil-shrike** [googleapis/python-automl#42]
For example - https://googleapis.dev/python/automl/latest/gapic/v1beta1/types.html?highlight=model#google.cloud.automl_v1beta1.types.ModelExportOutputConfig 

![image](https://user-images.githubusercontent.com/1203230/85136424-4a2bdf00-b248-11ea-946f-47a2602ac8aa.png)
All fields are listed twice, second time with some dummy descriptions:
![image](https://user-images.githubusercontent.com/1203230/85136573-79425080-b248-11ea-92eb-da9bcd7c855c.png)

**Comment by busunkim96** [comment]
Unfortunately this is unavoidable at the moment because of how we add docstrings to the protobuf types. Types should look much nicer once we move over to the microgenerator (coming early Q3)

**Comment by parthea** [comment]
I'm going to close this issue as obsolete as the issue does not appear in the [latest docs](https://googleapis.dev/python/automl/latest/automl_v1beta1/types.html).
