### ISSUE TITLE
automl tables tests are leaving leftover bigquery resources in test project

### ISSUE THREAD

**Issue by leahecole** [googleapis/python-automl#421]
Hi @balajismaniam - Yu-Han suggested I assign this to you - please feel free to ping me or set up time for further clarification

In the python-docs-samples-tests GCP project, [this test](https://github.com/googleapis/python-automl/blob/227c08b2fa6efa5af6677efc8e35382b23915fb4/samples/tables/batch_predict_test.py) is leaking resources. There are hundreds of BigQuery datasets with names like these:
```
prediction_do_not_delete_this_model_0_2022_08_11T12_41_05_118Z
prediction_do_not_delete_this_model_0_2022_08_11T12_43_15_121Z
prediction_do_not_delete_this_model_0_2022_08_11T12_43_38_220Z
```

I've been a detective for the past couple of days and have figured out that the name comes from a combination of a few things
* this "[static model](https://github.com/googleapis/python-automl/blob/227c08b2fa6efa5af6677efc8e35382b23915fb4/samples/tables/model_test.py#L29)" name
* [this comment](https://github.com/googleapis/python-automl/blob/227c08b2fa6efa5af6677efc8e35382b23915fb4/samples/tables/automl_tables_predict.py#L120) which explains the dataset name pattern

Could you please add a fixture that deletes the resource upon test completion, or, work with @ivanmkc to add these to reaper? 

If you need it, I can also help with the removal of the old datasets, but I wanted to leave them in place for your reference atm.

**Comment by meredithslota** [comment]
This library is planning to move to `google-cloud-python` — we will need to migrate the samples to `python-docs-samples`.  It may be worth looking at whether these samples are testing handwritten library features (if so, they should stay) or whether they are more demonstrative (they should migrate). Alternately, if any are obsolete, we should remove them during clean-up. @balajismaniam Is this something your team is planning to do?
