### ISSUE TITLE
Speed up samples job

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-automl#66]
The samples tests take ~20 minutes to complete.

Investigate to see if any modifications can be made to speed them up.

Logs note how much time each test takes:
https://source.cloud.google.com/results/invocations/b0462faf-1be8-41c6-83e4-e0b8ba27bc24/targets

**Comment by munkhuushmgl** [comment]
It is partly related to this issue.
Once this issue has been cleared up, we can take off pytest slow tags. 
I am also refactoring import and export tests to not use LRO.

https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3660#issuecomment-694507854

**Comment by munkhuushmgl** [comment]
Looks like current test duration reduced down to 12 min mark since most LRO operation sample tests just testing NotFound or some other exception.

With this note, Can i close this issue?

**Comment by busunkim96** [comment]
That sounds good! Thank you for addressing this.
