### ISSUE TITLE
ImportError: cannot import name 'service_pb2' from 'google.cloud.automl_v1.proto' (unknown location)

### ISSUE THREAD

**Issue by cmiller-nflux** [googleapis/python-automl#75]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-automl/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Windows 10 Jupyter Notebook
  - Python version: Python 3.7.6
  - pip version: pip 20.0.2
  - `google-cloud-automl` version: 2.0.0
  - `google-api-core` version: 1.22.2

#### Steps to reproduce

  1. Install the latest version of the AutoML package: python3 -m pip install --upgrade google-cloud-automl
  2. Try to import automl proto: from google.cloud.automl_v1.proto import service_pb2
  3. It fails

#### Code example

```python
from google.cloud.automl_v1.proto import service_pb2
```
#### Stack trace
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b0bc2a1681e9> in <module>
      3 from google.api_core.client_options import ClientOptions
      4 from google.cloud import automl_v1
----> 5 from google.cloud.automl_v1.proto import service_pb2
      6 
      7 def inline_text_payload(file_path):

ImportError: cannot import name 'service_pb2' from 'google.cloud.automl_v1.proto' (unknown location)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
If you need a type that used to be in`service_pb2`, 
 you can reference it directly under `automl` instead. https://github.com/googleapis/python-automl/blob/009085e0a82d1d7729349746c2c8954d5d60e0a9/google/cloud/automl_v1/types/service.py), 

```py
from google.cloud import automl

undeploy_request = automl.UndeployModelRequest(name="...")
export_request = automl.ExportModelRequest(name="...", output_config="...")

```

It might also be helpful to look through the samples https://github.com/googleapis/python-automl/tree/master/samples.

**Comment by cmiller-nflux** [comment]
Thank you
