### ISSUE TITLE
AutoML v1 API Does not seem to support AutoML Tables

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/python-automl#81]
AutoML v1beta1 API has Tables-related classes like `TablesDatasetMetadata`, but in v1 they no longer exist.

How can I work with tables in the v1 API? Are Tables deprecated?

#### Environment details

  - OS type and version: Linux
  - Python version: 3.6
  - `google-cloud-automl` version: 2.0.0

**Comment by busunkim96** [comment]
Hi @Ark-kun,

Tables is not available in v1, only in v1beta1. @sirtorry or @helinwang Do you have more context on this?

**Comment by sirtorry** [comment]
tables is only in v1beta1. we could discuss moving it into v1.

**Comment by helinwang** [comment]
Tables is a beta product, not a GA product. If I understand correctly, it should be in v1beta, not v1.
