### ISSUE TITLE
incorrect docstrings re: type_code (Tables)

### ISSUE THREAD

**Issue by amygdala** [googleapis/python-automl#99]
This example snippet (and possibly many others) are incorrect, as `type_code` no longer takes a string.

https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L1264

**Comment by tinyneutrino** [comment]
How can I correctly set the type code since I can't use e.g. `type_code='CATEGORY'`?
